import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
python:
  - '3.6'
language: python
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get -y install python3-gi gir1.2-gtk-3.0
  - pip3 install --quiet pylint
script:
  - PYTHONPATH=test-packages python3 -m pylint qubesbridgedevice
addons:
  apt:
    packages:
      - debootstrap
